### PR TITLE
Revert "Decision 8 Documenting quality dimensions"

### PR DESCRIPTION
**Pull request by BobBorges**
Reverts swerik-project/the-swedish-parliament-corpus#31

revert premature merge

### CODE REVIEW

**Comment by BobBorges** [comment]
I removed the prematurely merged documents from main and reintroduce them here. @MansMeg only minor edits to the decision doc -- templates look fine.

**Comment by MansMeg** [comment]
Can you edit the paragraph where I know say that the template should be included as a header in the unit test files?

**Comment by BobBorges** [comment]
> Can you edit the paragraph where I know say that the template should be included as a header in the unit test files?

So you want it to say what exactly?  In python, this would be a docstring, equivalent to a description... you can either import .md, write a docstring, or both... all this ends up in the API documentation. 

A short docstring is handy for people who look at the code and not the documentation.

**Comment by MansMeg** [comment]
Now it says the following:
> Each test should be stored as `test-[what-is-checked-automatically].py/r`. Each test should include a header in comment describing the test and why it has been included. See the data-integrity-test template.

What should it say on how we store the documentation? I guess we should store .md files? Maybe with the name `readme-[what-is-checked-automatically].md` ?

**Comment by BobBorges** [comment]
I think the quality estimate can also be stored as `test-[some-quality-dimension].py`. it's also a kind of test.

**Comment by MansMeg** [comment]
I think there is a difference, and we make a difference in our paper. I also think there is a qualitative difference between the two.
So, I would try to separate them. Say:
`qe-[some-quality-dimension].py` or similar.

**Comment by MansMeg** [comment]
I think it looks really good now!

**Review by MansMeg — APPROVED** [review]

**Pull request merged**
