### PR TITLE
Proposed API structure

### PR DESCRIPTION
**Pull request by MansMeg**
Hi!

Here is my proposed structure of the data repository apis. Feel free to comment.

### CODE REVIEW

**Comment by BobBorges** [comment]
Quality estimation is also a kind of test and uses similar conceptual workflows. I'm not sure I see the point in a separate folder. Instead:

```
test/                    # quality estimation code goes here along with integrity tests
test/data                # data goes here
test/quality-estimates   # versioned quality estimations
```

**Comment by ninpnin** [comment]
I would keep the gold standard data in its own folder.. test is very generic and only partially applicable

**Comment by MansMeg** [comment]
Ok. Whats your suggested solution Väinö?

**Comment by fredrik1984** [comment]
@ninpnin what do you think of this Väinö?

**Comment by ninpnin** [comment]
Sorry this is very late, but I would have the gold standard completely outside the test folder. What do you think?

**Comment by MansMeg** [comment]
How would you store it?

**Comment by ninpnin** [comment]
Have a _quality-data_ folder in the project root, at the same level as test etc. But I'm not necessarily planning to die on this hill

**Comment by MansMeg** [comment]
I think I agree with you here. So maybe have somethibg like this:

/quality/... -> scripts used for quality estimation
/quality/data/... -> data used for quality estimation
/quality/estimates/... -> estimates by version stored for easy access

**Comment by MansMeg** [comment]
Now I have updated the file with the decision we discussed. @fredrik1984 , you can now merge this.

**Pull request merged**
