### PR TITLE
Don't overwrite previous decisions

### PR DESCRIPTION
**Pull request by BobBorges**
.

### CODE REVIEW

**Review by ninpnin — APPROVED** [review]

**Comment by MansMeg** [comment]
I think the whole idea with git make this feasible. I changed decision 3 as a consequence of decision 8. I think that is ok. Since we want to be able to change decisions. Thats why we version control them.

**Comment by ninpnin** [comment]
A decision can only be overwritten by another decision?

**Comment by MansMeg** [comment]
Well. It is a decision to rewrite a previoys decision.

**Comment by BobBorges** [comment]
I think I'm happy so long as no edits can sneak past the review process, and we probably want to not only version control edits, but cross reference decisions somehow, so that if we edit 3 after 8, we also note in 3 that it was revised after 8 and/or in 8, 'this decision includes revision to 3'. Version control is great, but it doesn't necessarily tell us  *why* the decision was edited and I think that the logic behind the decisions we make should also be part of the documentation.

**Comment by BobBorges** [comment]
I've now also proposed decision 11 that amends 3 -- lets see if the convention seems reasonable to the others.

**Comment by fredrik1984** [comment]
Bob fix this.

**Pull request merged**
