### PR TITLE
Decision 5: no-party party affiliation

### PR DESCRIPTION
**Pull request by BobBorges**
How to store a no-party affiliation

### CODE REVIEW

**Review by MansMeg — APPROVED** [review]

**Review by ninpnin — APPROVED** [review]

**Review by fredrik1984 — COMMENTED** [review]
I know that we have been discussing this at different occasions. Maybe the parliament use "partilös" for MPs who do not belong to a party that is represented in the parliament. However, I don't like the concept "partilös" since it suggests that an MP is not a member of a party, which they often are but not a party that is represented in the parliament. To me, "vilde" feels more correct. I will just double check with Lotta about this.

**Comment by MansMeg** [comment]
Great. Whatever you settle on, we will use.

**Comment by fredrik1984** [comment]
Just got a response from Lotta: they use "Utan partibeteckning". This sounds actually better than both "partilös" and "vilde". Maybe we can call it "no party label" or "without party label" in English. @BobBorges which one of these two sounds less strange? Or do you have a better suggestion?

**Comment by MansMeg** [comment]
I would translate it to "Without party affiliation".

**Comment by fredrik1984** [comment]
"Independent politician" could work, and I also see that "Utan partibeteckning" is one of the aliases. And yes, it is convenient that there is a Wikidata page connected to it. "Without party affiliation" implies that there is no party attachment, which I think is wrong. 

Let's go with "Utan partibeteckning" + "Independent politician" for English translation (which is less important here)

**Comment by MansMeg** [comment]
Alright! I think everyone is now happy!

**Comment by fredrik1984** [comment]
So, then I merge, right? : )

**Comment by BobBorges** [comment]
Need to first edit the decision doc to include

```
## Status

Decided
- Decision: approved
``` 

then merge

**Pull request merged**
