### PR TITLE
Initialize decision handling

### PR DESCRIPTION
**Pull request by MansMeg**
Hi!

I have now started the process we ended up with and have this as a suggested solution. Feel free to test if this works with the adr-tool package (since I don't do Python). Also, feel free to comment and suggest stuff.

### CODE REVIEW

**Comment by BobBorges** [comment]
Excellent! I think we should also have a blank template file `docs/decisions/decision-template.md` -- it will be easy to just cp the file and fill in before a pr.

**Comment by ninpnin** [comment]
Looks good to me

**Comment by MansMeg** [comment]
Feel free to add the template to the PR bob

**Comment by MansMeg** [comment]
Excellent! Now we are waiting for @fredrik1984 to have an opinion.

**Comment by fredrik1984** [comment]
Ok, where do I find it? Sorry, always a bit lost in all this!

**Comment by BobBorges** [comment]
https://github.com/swerik-project/the-swedish-parliament-corpus/blob/decision-1/docs/decisions/decision-1.md

**Comment by fredrik1984** [comment]
I think it looks good too! Clean and simple.

**Pull request merged**
