### PR TITLE
Storing references to data points beyond the Biography Books

### PR DESCRIPTION
**Pull request by BobBorges**
[proposal](https://github.com/swerik-project/the-swedish-parliament-corpus/blob/decision-2/docs/decisions/decision-2.md)

### CODE REVIEW

**Comment by MansMeg** [comment]
I think this looks good. But I would love to get opinions from @ljo and @ninpnin

**Comment by BobBorges** [comment]
I also wanted to comment on Joakim's suggestion that the metadata could better be stored in a markup format. In general, he's right, and maybe it's something to think about for v2. It would definitely be a breaking change though, both in terms of the format of the metadata, but also in terms of a lot of the code we use.

**Comment by MansMeg** [comment]
Ping @ljo and @ninpnin .

**Comment by ninpnin** [comment]
Would these be edge cases, or would we store data in these files en masse?

**Comment by BobBorges** [comment]
The idea is more about fringe cases. So Bio-books are the standard source, but if, e.g., we know some piece of info is more accurate from another source, we store it in this way. But I'm not proposing that we add a bio-book reference to every datum in the corpus.

**Comment by ninpnin** [comment]
Apart from the folder structure – handled in the other decision – this seems fine to me

**Comment by MansMeg** [comment]
Great!

@fredrik1984 maybe you should formally merge this as the PI if you agree with it?

**Comment by fredrik1984** [comment]
done!

**Pull request merged**
